server:
  port: 9191

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Waka#123196
    url: jdbc:mysql://localhost:3306/userdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

transportation.url: http://localhost:8000/api/v1/transportation?truckId=

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# managed state of the circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      transportation:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        
#       If 50% of request from the service A to service B will fail, it would change the status to Open
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        # After 3 calls, it will determine the state: success -> Closed or fail -> Open
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
 